@ContactManager_HostAddress = http://localhost:5098/api

POST {{ContactManager_HostAddress}}/contacts
Content-Type: application/json
{
  "name":"test contact name",
  "phone":"01061816772",
  "address":"test address",
  "notes":"test notes"
}

###

GET {{ContactManager_HostAddress}}/contacts/66c13292-0870-4952-0112-08dd6f0c5c44
Content-Type: application/json
